# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-18 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('O', 'other'), ('M', 'Male')], max_length=1),
        ),
    ]
