# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-18 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20181218_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('O', 'other'), ('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
