# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-22 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_auto_20181220_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('write', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'help',
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('O', 'other'), ('F', 'Female')], max_length=1),
        ),
    ]
