# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-11 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_auto_20190101_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='help',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.Profile'),
        ),
    ]
