# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-11 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_auto_20190111_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='help',
            name='user',
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('O', 'other'), ('M', 'Male')], max_length=1),
        ),
    ]
