# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-12 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_auto_20190111_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('O', 'other'), ('F', 'Female')], max_length=1),
        ),
    ]
