# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-12 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_auto_20190112_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('O', 'other'), ('F', 'Female'), ('M', 'Male')], max_length=1),
        ),
    ]
