# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-22 06:02
from __future__ import unicode_literals

import Products.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Home', '0008_auto_20181222_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=99.99, max_digits=10)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('condition', models.CharField(choices=[('traditional', 'Traditional'), ('formal', 'Formal'), ('casual', 'Casual'), ('ethnic', 'Ethnic'), ('sports', 'Sports'), ('western', 'Western'), ('t-shirts', 'T-shirts'), ('kids', 'Kids'), ('jumpsuits', 'Jumpsuits'), ('denim', 'Denim'), ('winter', 'Winter war')], max_length=4)),
                ('category', models.CharField(choices=[('traditional', 'Traditional'), ('formal', 'Formal'), ('casual', 'Casual'), ('ethnic', 'Ethnic'), ('sports', 'Sports'), ('western', 'Western'), ('t-shirts', 'T-shirts'), ('kids', 'Kids'), ('jumpsuits', 'Jumpsuits'), ('denim', 'Denim'), ('winter', 'Winter war')], max_length=11)),
                ('occasion', models.CharField(choices=[('wedding', 'Wedding'), ('sangeet', 'Sangeet'), ('party', 'Party'), ('everyday', 'Everyday'), ('interview', 'Interview'), ('gym', 'Gym'), ('outings', 'Outings')], max_length=9)),
                ('featured', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sold', models.BooleanField(default=False)),
                ('image1', models.ImageField(upload_to=Products.models.upload_image_path)),
                ('image2', models.ImageField(blank=True, null=True, upload_to=Products.models.upload_image_path)),
                ('image3', models.ImageField(blank=True, null=True, upload_to=Products.models.upload_image_path)),
                ('image4', models.ImageField(blank=True, null=True, upload_to=Products.models.upload_image_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.Profile')),
            ],
            options={
                'db_table': 'Product',
            },
        ),
    ]
