# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-28 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_auto_20181228_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sell',
        ),
    ]
